### ISSUE TITLE
Include compiled PDF files along side .tex files

### ISSUE THREAD

**Issue by jakebesworth** [judiMc/programming_tools#9]
I believe that each tex file should be compiled and the included PDF files should be added to the repository.

It makes more sense from a portability perspective as most new programmers having access to a pdf reader more often than having access to a tex compiler. Also it helps that most browsers, and I believe Github in general has an inline pdf viewer, which allows the documents to be viewed inline the browser.

If we're using the browser, having a README per directory with nice markdown also makes sense, but much less practical than adding the PDFs.

I can compile recursively and add them myself, just want to know if this is a valid addition.

**Comment by judiMc** [comment]
My concern with that is that if we include the pdf in the repository every update to a latex file also requires  that someone  recompile and replace the pdf file, else we'll end up with the pdf out of synch.    I also don't mind that the cost of participation is learning to compile latex... but I can easily be convinced that is an unrealistic expectation.

**Comment by ian-james** [comment]
I agree, I think the PDF would easily fall out of sync, especially as we
include pull requests from students. I think it's a good suggestion though
to ease the learning curve.

Perhaps we could improve the README to have step by step directions for
updating the repo and compiling the review material into a pdf just to get
everyone started.

**Comment by judiMc** [comment]
good idea.  Let's update the README in the repo to include windows/os/x/linux instructions for setting up latex.  The makefile in each subfolder will compile as long as pdflatex is on the path.  Maybe less useful for windows users I guess.

**Comment by ian-james** [comment]
Sure, I'll update it soon.

**Comment by jakebesworth** [comment]
Hmm those are good suggestions. I think from a usability perspective, converting all the .tex into README.md files (readable in Github inline, and even then the source is more readable than LaTeX...) would probably be the best idea. Also this fixes our problem of needing 2 files, and no compilation, and no need for a LaTeX editor or compiler.

As another note, students have to compile all the files themselves (even if you use an IDE...) so I don't think the work to add to the Tex files and then compile and Pull Request is any different than students having to compile like 25 PDFs themselves (or open them in an editor and click "compile" / "run").

I think an updated root README is a good choice. The current way of having Tex files seems to afford more effort in viewing the information than if there were pre-compiled PDFs, or the use of README with markdown, but I guess that depends on the scope of, if we're trying to provide useful information as easily as possible, or if we're trying to get students to learn Tex and spend a bit more effort for the info, but also gain some knowledge along the way.

I'll leave the issue with these last thoughts, any decision is fine.

**Comment by keeferrourke** [comment]
LaTeX is an extremely useful to know, and everyone should be able to follow instructions to install an appropriate LaTeX distribution and run `make`... A lot of people are scared of or dismissive of using TeX, however I think it's an essential skil (and not a particularly difficult one to pick up) for document typesetting, particularly with respect to maths and computer sciences. Eventually people will be writing papers, and they will probably not want to be using MS Word or similar WYSIWYG editors.

**Comment by jakebesworth** [comment]
I agree with everything @keeferrourke , just if we were trying to make the repo not-guelph specific, it makes more sense to have a bunch of markdown READMEs which are human readable (via any text editor), and inline browser readable without the need of a compilation software OR a specific platform (e.g. LaTeX, or MS Word), AND it should be easier to write markdown than Tex... but regardless, it's up to the maintainer (Judi) to define the scope, so whether we're trying to provide the students with a learning experience (keep LaTeX) or provide this to the world, with useful knowledge, independent of anything (use markdown) doesn't matter, so keeping it as LaTeX makes sense, I agree.

A new README would be nice (compilation instructions, even per platform), I'll keep an eye out to see if I can contribute.

**Comment by jakebesworth** [comment]
Closing as we have the scope of the project defined by the maintainer.

**Comment by ian-james** [comment]
I certainly agree with previous statements that latex is a valued skill to learn and will help students throughout their academic careers. Even though the difference between html+others and latex should be shrinking in IMHO.

Anyway, I know this is closed, just wanted to comment,  I took a look at transforming the course material from latex to markdown using Pandoc. The transformation would require additional manual cleaning, not terrible but certainly several hours for someone. 

However, that doesn't include the additional time for maintaining consistency and other course development issues.
